title: "Julia Hagen"
descripiton: ""
author: "Julia Hagen"
permalink: pretty
excerpt_separator: <!--more-->
url: juliahagen.de

gems:
- jekyll-sass-converter
- jekyll-feed

sass:
    sass-dir: css
    style: :compressed
